packages:
  - packages/**
  - build/vite-plugin-about
  - build/vite-plugin-api
  - apps/docs
  - apps/admin

catalog:
  '@formatjs/intl-durationformat': ^0.10.0
  '@iconify/json': ^2.2.430
  '@solidjs/router': ^0.15.4
  '@solidjs/testing-library': ^0.8.10
  '@tailwindcss/vite': ^4.1.18
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^25.0.9
  '@vitest/coverage-v8': ^4.0.17
  autoprefixer: ^10.4.23
  bowser: ^2.13.1
  colorjs.io: ^0.6.1
  echarts: ^6.0.0
  intl-messageformat: ^11.1.1
  jsdom: ^27.4.0
  shiki: ^3.21.0
  solid-js: ^1.9.10
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  unplugin-icons: ^23.0.1
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-solid: ^2.11.10
  vite-plugin-static-copy: ^3.1.5
  vite-tsconfig-paths: ^6.0.4
  vitest: ^4.0.17
  vitest-fetch-mock: ^0.4.5
  yaml: ^2.8.2
  zod: ^4.3.5

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
