packages:
  - packages/**
  - build/vite-plugin-about
  - cmd/components
  - cmd/admin

catalog:
  '@iconify/json': ^2.2.369
  unplugin-icons: ^22.2.0
  '@types/node': ^24.2.1
  '@vitest/coverage-v8': ^3.2.4
  jsdom: ^26.1.0
  typescript: ^5.8.3
  vite: ^7.1.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-static-copy: ^3.1.1
  vitest: ^3.2.4
  vitest-fetch-mock: ^0.4.5
  vite-plugin-solid: ^2.11.8
  yaml: ^2.8.1
  postcss: ^8.5.6
  autoprefixer: ^10.4.21
  cssnano: ^7.1.0
  '@tailwindcss/vite': ^4.1.11
  '@solidjs/testing-library': ^0.8.10
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/user-event': ^14.6.1
  solid-devtools: ^0.34.3
  '@formatjs/intl-durationformat': ^0.7.4
  intl-messageformat: ^10.7.16
  '@solidjs/router': ^0.15.3
  solid-js: ^1.9.8
  tailwindcss: ^4.1.11

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
