packages:
  - packages/**
  - build/vite-plugin-about
  - build/vite-plugin-api
  - apps/docs
  - apps/admin

catalog:
  '@biomejs/biome': ^2.4.11
  '@iconify/json': ^2.2.461
  '@iconsets/svg-morpheus-ts': ^1.4.13
  '@microsoft/tsdoc': ^0.16.0
  '@scure/base': ^2.0.0
  '@solidjs/router': ^0.16.1
  '@solidjs/testing-library': ^0.8.10
  '@tailwindcss/vite': ^4.2.2
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^25.6.0
  '@vitejs/plugin-basic-ssl': ^2.3.0
  '@vitest/coverage-v8': ^4.1.4
  autoprefixer: ^10.4.27
  bowser: ^2.14.1
  browserslist: ^4.28.2
  browserslist-to-esbuild: ^2.1.1
  cbor2: ^2.3.0
  colorjs.io: ^0.6.1
  echarts: ^6.0.0
  fast-deep-equal: ^3.1.3
  intl-messageformat: ^11.2.0
  jsdom: ^29.0.2
  marked: ^18.0.0
  qr-code-styling: ^1.9.2
  quill: ^2.0.3
  shiki: ^4.0.2
  solid-js: ^1.9.12
  solid-transition-group: ^0.3.0
  tailwindcss: ^4.2.2
  ts-morph: ^27.0.2
  typescript: ^6.0.2
  unplugin-icons: ^23.0.1
  vite: ^8.0.8
  vite-plugin-dts: ^4.5.4
  vite-plugin-solid: ^2.11.12
  vitest: ^4.1.4
  vitest-fetch-mock: ^0.4.5
  yaml: ^2.8.3
  zod: ^4.3.6

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
