packages:
  - packages/**
  - build/vite-plugin-about
  - build/vite-plugin-api
  - apps/docs
  - apps/admin

catalog:
  '@formatjs/intl-durationformat': ^0.7.6
  '@iconify/json': ^2.2.416
  '@solidjs/router': ^0.15.4
  '@solidjs/testing-library': ^0.8.10
  '@tailwindcss/vite': ^4.1.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^25.0.0
  '@vitest/coverage-v8': ^4.0.15
  autoprefixer: ^10.4.22
  bowser: ^2.13.1
  colorjs.io: ^0.5.2
  echarts: ^6.0.0
  intl-messageformat: ^10.7.18
  jsdom: ^27.3.0
  shiki: ^3.19.0
  solid-js: ^1.9.10
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  vite: ^7.2.7
  vite-plugin-dts: ^4.5.4
  vite-plugin-solid: ^2.11.10
  vite-plugin-static-copy: ^3.1.4
  vitest: ^4.0.15
  vitest-fetch-mock: ^0.4.5
  yaml: ^2.8.2
  zod: ^4.1.13

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
