packages:
  - packages/**
  - build/vite-plugin-about
  - build/vite-plugin-api
  - cmd/docs
  - cmd/admin

catalog:
  '@formatjs/intl-durationformat': ^0.7.4
  '@iconify/json': ^2.2.386
  '@solidjs/router': ^0.15.3
  '@solidjs/testing-library': ^0.8.10
  '@tailwindcss/vite': ^4.1.13
  '@testing-library/jest-dom': ^6.8.0
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^24.5.2
  '@vitest/coverage-v8': ^3.2.4
  autoprefixer: ^10.4.21
  colorjs.io: ^0.5.2
  intl-messageformat: ^10.7.16
  jsdom: ^27.0.0
  shiki: ^3.13.0
  solid-js: ^1.9.9
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  unplugin-icons: ^22.3.0
  vite: ^7.1.6
  vite-plugin-dts: ^4.5.4
  vite-plugin-solid: ^2.11.8
  vite-plugin-static-copy: ^3.1.2
  vitest: ^3.2.4
  vitest-fetch-mock: ^0.4.5
  yaml: ^2.8.1

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
