# SPDX-FileCopyrightText: 2025-2026 caixw
#
# SPDX-License-Identifier: MIT

- pkg: "@cmfx/components"
  entrypoints:
      - entrypoint: "index.d.ts"
        types:
            - Chart.Props
            - Chart.Ref

            - ChartAxis.Props
            - ChartAxis.Ref
            - ChartAxis.XAxis
            - ChartAxis.Series

            - ChartPie.Props
            - ChartPie.Ref
