name: JSR-Publish

on:
    create:
        tags:
            - "v*"
            - "!v*-alpha"
            - "!v*-beta"

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - run: cd admin

            - name: Publish package
              run: npx jsr publish
