name: JSR-Publish

on:
    create:
        tags:
            - "v*"
            - "!v*-alpha"
            - "!v*-beta"

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 23
                  registry-url: https://registry.npmjs.org/

            - name: Install Deps
              run: npm install

            - name: test
              run: make build-ts

            # @cmfx/core

            - run: cd packages/core

            - name: Publish package @cmfx/core
              run: npx jsr publish

            # @cmfx/components

            - run: cd ../../packages/components

            - name: Publish package @cmfx/components
              run: npx jsr publish

            # @cmfx/admin

            - run: cd ../../packages/admin

            - name: Publish package @cmfx/admin
              run: npx jsr publish
