name: NPM-Publish

on:
    create:
        tags:
            - "v*"
            - "!v*-alpha"
            - "!v*-beta"

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 23
                  registry-url: https://registry.npmjs.org/

            - name: Install Deps
              run: npm install

            - name: build
              run: make build-ts

            # build @cmfx/core

            - name: publish @cmfx/core
              run: npm publish --access=public -w=@cmfx/core
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

            # build @cmfx/components

            - name: publish @cmfx/components
              run: npm publish --access=public -w=@cmfx/components
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

            # build @cmfx/admin

            - name: publish @cmfx/admin
              run: npm publish --access=public -w=@cmfx/admin
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
