name: NPM-Publish

on:
  create:
    tags:
    - 'v*'
    - '!v*-alpha'
    - '!v*-beta'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - name: build @cmfx/core
        run: npm run build -w=@cmfx/core

      - name: publish @cmfx/core
        run: npm publish --access=public -w=@cmfx/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: build @cmfx/admin
        run: npm run build -w=@cmfx/admin

      - name: publish @cmfx/admin
        run: npm publish --access=public -w=@cmfx/admin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
