name: Vitest
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: "23.x"

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Install Deps
              run: make install-ts

            - name: test
              run: make test-ts

            - name: Upload Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  files: ./coverage/report.json
